// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EspacioCliente.Data.Models
{
    public partial class BriefingDescargaFicheroResult
    {
        public string Descripcion { get; set; }
        public string Extension { get; set; }
        public byte[] Contenido { get; set; }
    }
}
