// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EspacioCliente.Data.Models;

public partial class Conversacion
{
    public int Id { get; set; }

    public int IdIncidencia { get; set; }

    public DateTime Fecha { get; set; }

    public int IdUsuario { get; set; }

    public string Texto { get; set; }

    public byte[] Imagen { get; set; }

    public virtual Incidencia IdIncidenciaNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}