// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using EspacioCliente.Data.Models;

namespace EspacioCliente.Data.Models
{
    public partial class EspacioClienteContext
    {

        [DbFunction("BriefingDescargaFichero", "dbo")]
        public static string BriefingDescargaFichero(int? idUsuario, int? id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
