// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using EspacioCliente.Data.Models;

namespace EspacioCliente.Data.Models
{
    public partial class EspacioClienteContext
    {

        [DbFunction("BriefingDescargaFichero", "dbo")]
        public IQueryable<BriefingDescargaFicheroResult> BriefingDescargaFichero(int? idUsuario, int? id)
        {
            return FromExpression(() => BriefingDescargaFichero(idUsuario, id));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BriefingDescargaFicheroResult>().HasNoKey();
        }
    }
}
