// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EspacioCliente.Data.Models;

public partial class Incidencia
{
    public int Id { get; set; }

    public int IdNodo { get; set; }

    public int IdUsuario { get; set; }

    public int Titulo { get; set; }

    public DateTime Fecha { get; set; }

    public bool Finalizado { get; set; }

    public virtual ICollection<Conversacion> Conversacion { get; set; } = new List<Conversacion>();

    public virtual Nodo IdNodoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}