// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EspacioCliente.Data.Models
{
    public partial class IncidenciasConversacionCrearEntradaResult
    {
        public int Id { get; set; }
        public int IdIncidencia { get; set; }
        public DateTime Fecha { get; set; }
        public int id { get; set; }
        public string Login { get; set; }
        public string Texto { get; set; }
        public byte[] Imagen { get; set; }
    }
}
