// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EspacioCliente.Data.Models;

public partial class Log
{
    public int Id { get; set; }

    public DateTime Fecha { get; set; }

    public string Texto { get; set; }
}