// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EspacioCliente.Data.Models;

public partial class Orden
{
    public int Id { get; set; }

    public int IdInsercion { get; set; }

    public int Presupuesto { get; set; }

    public decimal Inversion { get; set; }

    public virtual Insercion IdInsercionNavigation { get; set; }
}