// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EspacioCliente.Data.Models;

public partial class Plan
{
    public int Id { get; set; }

    public int IdNodo { get; set; }

    public string Descripcion { get; set; }

    public DateOnly Inicio { get; set; }

    public DateOnly Fin { get; set; }

    public int Medio { get; set; }

    public virtual Nodo IdNodoNavigation { get; set; }

    public virtual ICollection<Insercion> Insercion { get; set; } = new List<Insercion>();

    public virtual Medio MedioNavigation { get; set; }
}