// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EspacioCliente.Data.Models;

public partial class TipoNodo
{
    public int Id { get; set; }

    public string TipoNodo1 { get; set; }

    public virtual ICollection<Nodo> Nodo { get; set; } = new List<Nodo>();
}