// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EspacioCliente.Data.Models;

public partial class UsuarioNodo
{
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public int IdNodo { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}