// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EspacioCliente.Data.Models;

public partial class Valla
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public string Latitud { get; set; }

    public string Longitud { get; set; }

    public int IdOri { get; set; }

    public virtual ICollection<Insercion> Insercion { get; set; } = new List<Insercion>();
}